config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    authenticated :user do
      root 'events#index', as: :authenticated_root
    end

    root to: 'pages#index'

    resources :events do
      resources :teams
      resources :teams_applications
      resources :shifts
      resources :requirements
      resources :availabilities
      resources :statistics, only: [:index]
      resources :schedules do
        collection do
          get :generate, to: 'schedules#generate'
          get :admin, to: 'schedules#admin'
        end
      end
    end

    namespace :admin do
      root 'users#index'
      resources :users, only: [:index]
    end
  end
end

app/models/schedule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules
#
#  id         :bigint(8)        not null, primary key
#  user_id    :bigint(8)
#  shift_id   :bigint(8)
#  team_id    :bigint(8)
#  event_id   :bigint(8)
#  comment    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  position   :integer
#  mandatory  :boolean
#


class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :shift
  belongs_to :team
  belongs_to :event
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  respond_to :html, :js
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @event = Event.find(params[:event_id])
    schedules = @event.schedules
    if @current_user.is? :user
      schedules = schedules.select { |s| s[:user_id] == @current_user.id }
    end
    teams = Team.where(event_id: @event.id)
    shifts = Shift.where(event_id: @event.id)
    users = User.all
    @resources = []
    @events = []

    teams.each do |t|
      resource = { id: t[:id], name: t[:title] }
      @resources << resource
    end

    schedules.each_with_index do |s, index|
      shift = shifts.detect { |sh| sh[:id] == s[:shift_id] }
      user = users.detect { |u| u[:id] == s[:user_id] }
      event = { id: index + 1, start: shift[:start_time].strftime('%Y-%m-%d %H:%M:%S'), end: shift[:end_time].strftime('%Y-%m-%d %H:%M:%S'),
                resourceId: s[:team_id], title: "#{user[:first_name]} #{user[:last_name]}", bgColor: '#1F83D1' }
      event[:bgColor] = 'red' unless defined?(user)
      @events << event
    end
    @events.sort_by! { |x| Date.parse x[:start] }
  end

  def admin
    @event = Event.find(params[:event_id])
    @schedule = Schedule.where(event_id: @event.id)
  end

  def edit
    @event = Event.find(params[:event_id])
    @schedule = Schedule.find(params[:id])
  end

  def update
    @event = Event.find(params[:event_id])
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      flash[:success] = 'Schedule was successfully updated'
      redirect_to event_schedules_path(@event)
    else
      flash[:danger] = 'Error updating schedule'
      render 'edit'
    end
  end

  def generate
    @event = Event.find(params[:event_id])
    @shifts = @event.shifts.order(:start_time)
    @requirements = @event.requirements
    @availabilities = Availability.joins(:shift).where(shifts: { event_id: @event.id })
    @applications = @event.teams_applications

    # Create Schedule array containing all shifts according to their requirements
    @schedule = create_schedule(@shifts, @requirements, @event[:id])

    # creates priority table container the number of required users in a shift and the number of available people
    # then sorts by least requirement and least availability
    priority_table = create_priority(@requirements, @shifts, @availabilities).sort_by { |p| [p[:requirements], p[:availabilities]] }

    # iterate through item in priority table
    priority_table.each_with_index do |p, index|
      # skip if there is no requirement or no availability
      if p[:requirements] != 0 || p[:availabilities] != 0
        # retrieve all schedules at the current shift based on the order of priority table
        priority_schedule = @schedule.select { |s| s[:shift_id] == p[:shift] }
        # retrieve all availabilities at current shift
        availabilities = @availabilities.select { |a| a[:shift_id] == p[:shift] }
        # if availabilities and requirements equals 1, add user to schedule
        if p[:availabilities] == 1 && p[:requirements] == 1
          @schedule[@schedule.index(priority_schedule[0])][:user_id] = availabilities[0][:user_id]
        else
          begin
            priority_schedule.each do |p_s|
              next if match(availabilities, p_s, @applications, @shifts, @schedule, 1) == true
              next if match(availabilities, p_s, @applications, @shifts, @schedule, 2) == true
              next if match(availabilities, p_s, @applications, @shifts, @schedule, 3) == true
            end
          rescue StandardError => e
            puts e
            puts
          end
        end
      end
      puts "done: #{index + 1} / #{priority_table.length}"
    end

    @schedule.each(&:save) if Schedule.where(event_id: @event.id).blank?

    redirect_to event_schedules_path(@event)
  end

  private

  # iterate through all availabilities in a shift. Find all users that are available for that shift. passing through
  # every schedule at a given shift, add the user if the current schedule's team corresponds to the level of priority
  # that the user assigned
  def match(availabilities, priority_schedule, all_applications, all_shifts, all_schedules, priority)
    availabilities.each do |availability|
      next if user_tired(availability[:shift_id], availability[:user_id], all_shifts, all_schedules)

      # find all user team applications at an availability
      team_application = all_applications.select { |app| app[:user_id] == availability[:user_id] && app[:team] == priority_schedule[:team] }
      team_application.each do |application|
        if priority == application[:priority] && all_schedules.detect { |s| s == priority_schedule }[:user_id].blank?
          all_schedules.detect { |s| s == priority_schedule }[:user_id] = availability[:user_id]
          return true
        end
      end
    end
    false
  rescue StandardError => e
    puts e
  end

  # verifies if user has a shift before or after
  def user_tired(shift_id, user_id, shifts, schedules)
    shift_index = shifts.index { |s| s[:id] == shift_id }
    current_schedules = schedules.select { |s| s[:shift_id] == shifts[shift_index][:id] }
    schedules_before = schedules.select { |s| s[:shift_id] == shifts[shift_index - 1][:id] }
    schedules_after = schedules.select { |s| s[:shift_id] == shifts[shift_index + 1][:id] }
    # return true if a shift is found in the period before, current or next
    if current_schedules.any? { |s| s[:user_id] == user_id } || schedules_before.any? { |s| s[:user_id] == user_id } || schedules_after.any? { |s| s[:user_id] == user_id }
      return true
    else
      return false
    end
  end

  def create_priority(requirements, shifts, availabilities)
    priority_table = []
    shifts.each do |s|
      requirement_shifts = requirements.select { |r| r[:shift_id] == s.id }
      total_requirements = 0
      requirement_shifts.each do |r|
        total_requirements += r.mandatory + r.optional
      end
      availabilities_shift = availabilities.select { |a| a[:shift_id] == s.id }
      total_availabilities = availabilities_shift.count
      priority_table << { shift: s.id, requirements: total_requirements, availabilities: total_availabilities }
    end

    priority_table
  end

  def create_schedule(shifts, all_requirements, current_event_id)
    schedule = []
    shifts.each do |s|
      requirements = all_requirements.select { |r| r[:shift_id] == s[:id] }
      requirements.each do |r|
        (r.mandatory + r.optional).times do |i|
          schedule << Schedule.new(event_id: current_event_id,
                                   shift_id: s.id,
                                   team_id: r[:team_id],
                                   position: i + 1,
                                   mandatory: (i + 1 <= r.mandatory))
        end
      end
    end
    schedule
  end

  def schedule_params
    params.require(:schedule).permit(:user_id, :comment)
  end
end

app/views/schedules/admin.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to @event.title, event_path(@event) %>
    </li>
    <li class="breadcrumb-item active">Scheduling tools</li>
  </ol>
  <div class="row">
    <div class="col-12">
      <% if @schedule.empty? %>
        <h1>Scheduling Tools</h1>
        <hr>
        <div class="card col-md-3">
          <%= image_tag 'https://vignette.wikia.nocookie.net/starwars/images/9/9a/Palp_trustme.jpg/revision/latest/scale-to-width-down/250?cb=20070114040526', class: 'card-img-top' %>
          <div class="card-body">
            <%= link_to 'Do it', generate_event_schedules_path(event_id: @event),id: 'generate-schedule', class: 'btn btn-primary'%>
          </div>
        </div>
        <div id="generate-schedule" style="display:none;"></div>

      <% else %>
        <div class="card mb-3">
          <div class="card-header">
            <h1><i class="fa fa-table"></i> Schedule</h1>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th> Schedule #</th>
                  <th> User</th>
                  <th>Shift</th>
                  <th>Job (team id + position)</th>
                  <th>Comments</th>
                  <% if can? :manage, Schedule %>
                    <th>Action</th>
                  <% end %>
                </tr>
                </thead>
                <tbody>
                <% @schedule.each_with_index do |s, index| %>
                  <tr>
                    <td> <%= index + 1 %> </td>
                    <td>
                      <% if s.user_id.present? %>
                        <%= s.user.full_name %>
                      <% end %>
                    </td>
                    <td>
                      <%= s.shift.shift_name %>
                      <% if s.mandatory == true %>
                        <p class="text-danger">Mandatory Shift</p>
                      <% else %>
                        <p class="text-warning">Optional Shift</p>
                      <% end %>
                    </td>
                    <td><%= s.team.title %> <%= s.position %> </td>
                    <th><%= s.comment %></th>
                    <% if can? :manage, Schedule %>
                      <th>
                        <%= link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_event_schedule_path(event_id: @event, id: s) %>
                      </th>
                    <% end %>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to @event.title, event_path(@event) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to 'Schedule Tools', admin_event_schedules_path(@event) %>
    </li>
    <li class="breadcrumb-item active">
      Edit
    </li>
  </ol>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">Edit shift: <%= @schedule.shift.shift_name %></h2>
      <h4> <%= @schedule.team.title %> Team, position: <%= @schedule.position %></h4>
    </div>

    <br>

    <div class="card-body">
      <%= render 'shared/errors', object: @schedule %>

      <%= form_for [@event, @schedule] do |t| %>
        <div class="form-group">
          <%= t.label :user %>
          <%= collection_select(:schedule, :user, User.all, :id, :full_name, {prompt: true, required: true},  {class: 'form-control'}) %>
        </div>
        <div class="form-group">
          <%= t.label :comment %>
          <%= t.text_area :comment, class: 'form-control' %>
        </div>
        <div class="btn-group-justified">
          <%= t.submit "Update", class: 'btn btn-primary' %>
          <%= link_to "Back to Schedule tools ",admin_event_schedules_path(@event), class: "btn btn-outline-danger" %>
        </div>

      <% end %>
    </div>
  </div>
<% end %>

app/views/schedules/generate.html.erb
<h3>Generating is done!</h3>
<p>Refresh your page</p>

app/views/schedules/generate.js.erb
window.location.reload(true);
/*
$('#generate-schedule').html("<%= j render 'generate' %>");
$('#generate-schedule').slideDown(350);
*/

app/views/schedules/index.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to @event.title, event_path(@event) %>
    </li>
    <li class="breadcrumb-item active">Schedule</li>
  </ol>
  <div class="row">
    <div class="col-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Schedule</h1>
        </div>
        <div class="panel-body" >
          <%= react_component('SchedulerViewer', {resources: @resources, events: @events, eventDate: @event[:start_date].strftime('%Y-%m-%d %H:%M:%S')}) %>
        </div>
      </div>

    </div>
  </div>

<% end %>