config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    authenticated :user do
      root 'events#index', as: :authenticated_root
    end

    root to: 'pages#index'

    resources :events do
      resources :teams
      resources :teams_applications
      resources :shifts
      resources :requirements
      resources :availabilities
      resources :statistics, only: [:index]
      resources :schedules do
        collection do
          get :generate, to: 'schedules#generate'
          get :admin, to: 'schedules#admin'
        end
      end
    end

    namespace :admin do
      root 'users#index'
      resources :users, only: [:index]
    end
  end
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id         :bigint(8)        not null, primary key
#  title      :string(255)
#  start_date :datetime
#  end_date   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Event < ApplicationRecord
  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  # belongs_to :user, optional: true
  has_many :teams
  has_many :teams_applications
  has_many :shifts
  has_many :requirements
  has_many :schedules
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Event controllers
class EventsController < ApplicationController
  load_and_authorize_resource

  def index
    @events = Event.all
    authorize! :index, @event
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = 'Event was successfully created'
      redirect_to events_path
    else
      flash[:danger] = 'Error creating Event'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @schedule_not_created = Schedule.where(event_id: @event).empty?
    @schedules = Schedule.where(event_id: @event, user_id: @current_user.id)
    shifts = Shift.where(id: @schedules.map(&:shift_id))
    @total_hours = 0
    @schedules.each do |s|
      shift = shifts.detect { |sh| sh[:id] == s[:shift_id] }
      @total_hours += ((shift[:end_time] - shift[:start_time]) / 3600).to_i
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = 'Event was successfully updated'
      redirect_to event_path(@event)
    else
      flash[:danger] = 'Error updating Event'
      render 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :start_date, :end_date)
  end
end

app/views/events/edit.html.erb
<% content_for :top_content do %>
<div class="panel panel-default col-6">
  <div class="panel-heading"><h2>Edit <%= @event.title %></h2></div>
  <div class="panel-body col-6">
    <%= render 'shared/errors', object: @event %>
  </div>

  <%= form_for @event do |f| %>
  <div class="form-group">
    <%= f.label :title %> <%= f.text_field :title, class:
    'form-control',required: true %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %> <%= f.date_field :start_date,
    class:'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :end_date%> <%= f.date_field :end_date, class:
    'form-control',required: true%>
  </div>
  <div class="btn-group-justified">
    <%= f.submit "Update", class: 'btn btn-primary' %> <%= link_to "Back to
    events listing", events_path, class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>
<% end %>

app/views/events/index.html.erb
<% content_for :top_content do %>
  <div class="row">
    <div class="col-12">
      <div class="panel panel-default">
        <% if can? :create, Event %>
          <%= link_to 'Created new event', new_event_path, class: 'btn btn-primary btn-lg' %>
          <hr>
        <% end %>
        <div class="panel-heading">
          <h2>Upcoming events</h2>
        </div>
        <div class="panel-body">
          <div class="row">
            <% @events.each do |e| %>
              <% if e.start_date >= Time.now %>
                <div class="col-xl-3 col-sm-8 col-md-4 mb-3">
                  <div class="card text-white bg-info o-hidden h-100">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <div class="card-title">
                        <h2><%= e.title %></h2>
                      </div>
                      <div class="card-text">
                        <p>Start:
                          <%= e.start_date.strftime('%A %B %d %Y') %></p>
                        <p>End:
                          <%= e.end_date.strftime('%A %B %d %Y') %></p>
                      </div>
                      <div class="card-footer">
                        <% if can? :edit, @events %>
                          <%= link_to '<span >Edit</span>'.html_safe, edit_event_path(e), class: 'text-white card-link' %>
                        <% end %>
                        <%= link_to '<span class="float-right"> Go <i class="fa fa-angle-right"></i> </span>'.html_safe, e, class: 'text-white card-link' %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="panel-heading">
          <h2>Past events</h2>
        </div>
        <div class="panel-body">
          <div class="row">
            <% @events.each do |e| %>
              <% if e.start_date < Time.now %>
                <div class="col-xl-3 col-sm-8 col-md-4 mb-3">
                  <div class="card text-white o-hidden h-100" style="background-color:#595959">
                    <div class="card-body">
                      <div class="card-body-icon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <div class="card-title">
                        <h2><%= e.title %></h2>
                      </div>
                      <div class="card-text">
                        <p>Start:
                          <%= e.start_date.strftime('%A %B %d %Y') %></p>
                        <p>End:
                          <%= e.end_date.strftime('%A %B %d %Y') %></p>
                      </div>
                      <div class="card-footer">
                        <% if can? :edit, @events %>
                          <%= link_to '<span >Edit</span>'.html_safe, edit_event_path(e), class: 'text-white card-link' %>
                        <% end %>
                        <%= link_to '<span class="float-right"> Go <i class="fa fa-angle-right"></i> </span>'.html_safe, e, class: 'text-white card-link' %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<% content_for :top_content do %>
<div class="row">
  <h1 class="col-md-6"> Create a new event </h1>
</div>


<%= render 'shared/errors', object: @event %>

<%= form_for @event do |f| %>
  <div class="form-group col-md-6">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, class: 'form-control', required: true %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :end_date%>
    <%= f.date_field :end_date, class: 'form-control', required: true%>
  </div>
  <div class="col-md-6">
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <%= link_to "Back", :back,  class: "btn btn-outline-danger"  %>
  </div>

<% end %>

<% end %>

app/views/events/show.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= @event.title %>
    </li>
    <li class="breadcrumb-item active">Dashboard</li>
  </ol>

  <div class="row">
    <div class="col-12">
      <h2><%= @event.title %> (<%= @event.start_date.strftime('%a %b %d %Y') %>
        - <%= @event.end_date.strftime('%a %b %d %Y') %>) </h2>
      <%= link_to "Back to events listing", events_path, class: "btn btn-outline-danger" %>
      <div class="col-6 card">
        <div class="card-header">
          <h1>Schedule</h1>
        </div>
        <div class="card-body">
          <% if @current_user.is? (:admin) %>
          <div class="card col-md-8 bg-primary">
            <%= image_tag "https://i.imgur.com/XABoTRz.png", class: 'card-img-top img-fluid' %>
            <div class="card-body">
              <p class="text-white">Silly <%= @current_user.first_name %>, Admins should always be present at the event!</p>
            </div>
          </div> 


          <% elsif @schedules.empty? && @schedule_not_created %>
            <p>Schedule has not been created yet. Wait or contact the person in charge</p>
          <% elsif @schedules.empty? && !@schedule_created %>
            <p>You are not assigned a shift. Contact the person in charge</p>
          <% else %>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-dark">
                <tr>
                  <th>Shift</th>
                  <th>Team</th>
                  <th>Comment</th>
                </tr>
                </thead>
                <tbody>
                <% @schedules.each do |s| %>
                  <tr>
                    <td><%= s.shift.shift_name %></td>
                    <td><%= s.team.title %></td>
                    <td>
                      <%= s.comment.present? ? s.comment : "" %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-6 card mt-2">
        <div class="card-header">
          <h1>Event Stats</h1>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead class="thead-dark">
              <tr>
                <td>Resource</td>
                <td>Data</td>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>Total Hours</td>
                <td><%= @total_hours %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>


<% end %>