config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    authenticated :user do
      root 'events#index', as: :authenticated_root
    end

    root to: 'pages#index'

    resources :events do
      resources :teams
      resources :teams_applications
      resources :shifts
      resources :requirements
      resources :availabilities
      resources :statistics, only: [:index]
      resources :schedules do
        collection do
          get :generate, to: 'schedules#generate'
          get :admin, to: 'schedules#admin'
        end
      end
    end

    namespace :admin do
      root 'users#index'
      resources :users, only: [:index]
    end
  end
end

app/models/shift.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: shifts
#
#  id         :bigint(8)        not null, primary key
#  start_time :datetime
#  end_time   :datetime
#  event_id   :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Shift < ApplicationRecord
  belongs_to :event, optional: true
  has_and_belongs_to_many :users
  has_many :requirements
  has_many :availabilities

  def shift_name
    "#{start_time.strftime('%A %B %d - %k:%M')} to #{end_time.strftime('%A %B %d - %k:%M')}"
  end
end

app/controllers/shifts_controller.rb
# frozen_string_literal: true

class ShiftsController < ApplicationController
  load_and_authorize_resource

  def index
    @event = Event.find(params[:event_id])
    @shifts = @event.shifts
    @availabilities = Availability.joins(:shift).where(availabilities: { user_id: @current_user.id }, shifts: { event_id: @event.id })
  end

  def new
    @event = Event.find(params[:event_id])
    @shift = Shift.new
  end

  def create
    @event = Event.find(params[:event_id])
    @shift = Shift.new(shift_params)
    DateTime.strptime(@shift.start_time.to_s, '%Y-%m-%d %H:%M')
    DateTime.strptime(@shift.end_time.to_s, '%Y-%m-%d %H:%M')
    if @shift.save
      flash[:success] = 'Shift was successfully created'
      @event.shifts << @shift
      redirect_to event_shifts_path(@event)
    else
      flash[:danger] = 'Error creating Shift'
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @shift = Shift.find(params[:id])
  end

  def update
    @event = Event.find(params[:event_id])
    @shift = Shift.find(params[:id])
    if @shift.update(shift_params)
      flash[:success] = 'Shift was successfully updated'
      redirect_to event_shifts_path(@event)
    else
      flash[:danger] = 'Error updating Shift'
      render 'edit'
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:start_time, :end_time)
  end
end

app/views/shifts/edit.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to @event.title, event_path(@event) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Shifts ", event_shifts_path(@event) %>
    </li>
    <li class="breadcrumb-item active">
      Edit
    </li>
  </ol>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">Edit shift: <%= @shift.shift_name %></h2>
    </div>

    <br>

    <div class="panel-body">
      <%= render 'shared/errors', object: @shift %>

      <%= react_component('ShiftForm', {shift: @shift, event: @event, edit: true}) %>
      <%= link_to "Back to Shifts ", event_shifts_path(@event), class: "btn btn-outline-danger" %>
    </div>
  </div>
<% end %>

app/views/shifts/index.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to @event.title, event_path(@event) %>
    </li>
    <li class="breadcrumb-item active">
      Shifts
    </li>
  </ol>

  <div class="row">
    <div class="col-12">
      <% if @shifts.empty? %>
        <h1>Shifts of <%= @event.title %> </h1>
        <hr>
        <div class="jumbotron">
          <h3> No shifts found </h3>
          <% if can? :create, Shift %>
            <p> Start creating shifts here </p>
            <%= link_to 'Create new shifts here', new_event_shift_path(event_id: @event), class: 'btn btn-primary' %>
          <% end %>
        </div>

      <% else %>
        <div class="card mb-3">
          <div class="card-header">
             <h1><i class="fa fa-table"></i> Shifts</h1>
          </div>
          <div class="card-body">
            <div class="btn-group-justified mb-2">
              <% if can? :create, Shift %>
                <%= link_to 'Create new shifts here', new_event_shift_path(event_id: @event), class: 'btn btn-primary' %>
                <%= link_to 'View all availabilities ', event_availabilities_path(event_id: @event), class: 'btn btn-info' %>
              <% end %>
              <%= link_to 'Submit new availability', new_event_availability_path(event_id: @event), class: 'btn btn-success' %>
            </div>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-dark">
                <tr>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th>Availability</th>
                  <% if can? :manage, Shift %>
                  <th>Admin Actions</th>
                  <% end %>
                </tr>
                </thead>
                <tbody>
                <% @shifts.each do |s| %>
                  <tr>
                    <td><%= s.start_time.strftime('%A %B %d - %k:%M') %></td>
                    <td> <%= s.end_time.strftime('%A %B %d - %k:%M') %> </td>
                    <td>
                      <% if @availabilities.any? {|a| a.shift_id == s.id} %>
                        <p class="text-warning">Submitted</p>
                      <% else %>
                        <p class="text-danger">Not Available</p>
                      <% end %>
                    </td>
                    <% if can? :manage, Shift %>
                      <td>
                        <%= link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_event_shift_path(event_id: @event, id: s) %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>

      <% end %>
    </div>

  </div>
<% end %>

app/views/shifts/new.html.erb
<% content_for :top_content do %>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to @event.title, event_path(@event) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Shifts ", event_shifts_path(@event) %>
    </li>
    <li class="breadcrumb-item active">
      New
    </li>
  </ol>

  <div class="panel panel-default col-12">
      <div class="panel-heading">
        <h2 >Create new shift</h2>
      </div>
      <div class="panel-body">
        <%= render 'shared/errors', object: @shift %>

        <%= react_component('ShiftForm', {shift: @shift, event: @event}) %>
        <%= link_to "Back", :back,  class: "btn btn-outline-danger"  %>
      </div>
  </div>

<% end %>