config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    authenticated :user do
      root 'events#index', as: :authenticated_root
    end

    root to: 'pages#index'

    resources :events do
      resources :teams
      resources :teams_applications
      resources :shifts
      resources :requirements
      resources :availabilities
      resources :statistics, only: [:index]
      resources :schedules do
        collection do
          get :generate, to: 'schedules#generate'
          get :admin, to: 'schedules#admin'
        end
      end
    end

    namespace :admin do
      root 'users#index'
      resources :users, only: [:index]
    end
  end
end

app/views/layouts/_header.html.erb
<ul class="navbar-nav ml-auto">
<%= render 'shared/change_locale' %>
  <% if user_signed_in? %>
    <% if can? :manage, :admin %>
      <li class="nav-item mr-sm-2">
        <%= link_to "Admin", admin_root_path(), class: 'nav-link' %>
      </li>
    <% end %>
    <li class="nav-item">
      <%= link_to t('header.edit_account'), edit_user_registration_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to t("header.log_out_html"), destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
    </li>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
  <ul class="navbar-nav navbar-sidenav " id="exampleAccordion">
    <li class="nav-item mb-2 mt-4" data-toggle="tooltip" data-placement="right" title="Dashboard">
      <%= link_to '<i class="fa fa-tachometer"></i> <span class="font-weight-bold">Dashboard</span>'.html_safe, @event, class: 'nav-link ' %>
    </li>
    <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Teams">
      <%= link_to '<i class="fa fa-users"></i> <span class="font-weight-bold">Teams</span>'.html_safe, event_teams_path(@event), class: 'nav-link' %>
    </li>
    <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Shifts">
      <%= link_to '<i class="fa fa-hourglass-start"></i> <span class="font-weight-bold">Shifts</span>'.html_safe, event_shifts_path(@event), class: 'nav-link' %>
    </li>
    <% if can? :manage, Requirement %>
      <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Requirements">
        <%= link_to '<i class="fa fa-clipboard"></i> <span class="font-weight-bold">Requirements</span>'.html_safe, event_requirements_path(@event), class: 'nav-link' %>
      </li>
      <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Tools">
        <%= link_to '<i class="fa fa-wrench"></i> <span class="font-weight-bold">Schedule Tools</span>'.html_safe, admin_event_schedules_path(@event), class: 'nav-link' %>
      </li>
    <% end %>

    <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Schedule">
      <%= link_to '<i class="fa fa-calendar"></i> <span class="font-weight-bold">Schedule</span>'.html_safe, event_schedules_path(@event), class: 'nav-link' %>
    </li>
    <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Import">
      <a class="nav-link" href="#"><i class="fa fa-download"></i>
        <span class="font-weight-bold">Import/Export</span></a>
    </li>
    <% if can? :manage, :all %>
      <li class="nav-item mb-2" data-toggle="tooltip" data-placement="right" title="Import">
        <%= link_to '<i class="fa fa-bar-chart"></i> <span class="font-weight-bold">Stats</span>'.html_safe, event_statistics_path(@event), class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Volops</title>
  <meta charset="UTF-8">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/react-datepicker/1.5.0/react-datepicker.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' %>
  <%= favicon_link_tag 'panda.ico' %>

</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <%= link_to 'Volops', root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <%= render :partial => "layouts/header" %>
    <% unless @event.blank? %>
      <% if !!@event.try(:id) %>
        <%= render :partial => "layouts/sidebar" %>
      <% end %>
    <% end %>
  </div>


</nav>

<div class="content-wrapper">
  <div class="container-fluid">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  </div>

  <div class="container-fluid">
    <%= yield %>
    <%= yield :top_content %>

    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Lan ETS 2018</small>
        </div>
      </div>
    </footer>
  </div>

</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
</body>

</html>